import Head from 'next/head'
import Image from 'next/image'
import Galery from '../components/Galery'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <>    
      <Head>
        <title>Ju Rosas|Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Compre já suas Rosas do Deserto' message='Aqui você encontrara desde enxertos a sementes até bonsais de rosas ja grandes, click abaixo e descubra mais!!' buttonName='Ver Estoque !'></Hero>
      <Galery />
    </>
  )
}
